### ISSUE TITLE
Make smaller commits

### ISSUE THREAD

**Issue by cjessett** [bahobab/gather-phase-4#1]
(Important) Although this might be a small project, it's important to make small commits. This allows developers to follow your work and understand how changes were made. As a rule of thumb I like to make at least 1 commit per feature, sometimes a feature will require multiple commits. Here is post on writing good commit message http://who-t.blogspot.com/2009/12/on-commit-messages.html

**Comment by bahobab** [comment]
Thanks CJ. Will keep this in mind for future projects
