### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [bahobab/gather-phase-4#4]
(Meets Expectations) Overall, nice job.

Remember to make smaller commits, think at least 1 commit per feature/route/test file. Also, remember to use es6 features like object shorthand assignment when possible.

Otherwise, very nice test coverage of your routes and models! Great job!

**Comment by bahobab** [comment]
All the remarks are right on and will observe them for future projects. Thanks so much CJ for your reviews comments and advice.
